export const scaleFactor = 4;

export const dialogueData = {
    exit: 'You can exit this place by closing the tab in your browser.',
    computer: `This is my PC... in the dungeon... why is there a computer in the dungeon you may ask... It is just to say thank you for taking the 
    time play through my little educational history and to share some links.
    I do have a <a href="https://www.linkedin.com/in/jason-whitby-mscsia-bb16051b9/" target="_blank">LinkedIn</a> page to show all of this stuff. 
    You can also contact me quite easily through there as well. I also have a 
    <a href="https://github.com/735783D" target="_blank">Github</a> repo where I keep my previous school work, small security projects,
    and some artistic stuff. There are also some videos on YouTube that show a little bit of my tiny animation skills if you are 
    interested <a href="https://www.youtube.com/watch?v=-EnahxXbyl4" target="_blank">ClaireAndWraith v2</a>, <a href="https://youtube.com/shorts/kAr5Tu9y57Y" target="_blank">Jason\'s Cinnamon Sugar Donut</a>, and my first animation the <a href="https://youtube.com/shorts/BKmSWTWTMNY" target="_blank">Finished Donut!</a>. But, thank you again for taking the journey with me. 
    And, did you find the easter egg...?`, 
    sword1: `This sword is half of the representation of an organization that I am a member of. Have you heard of the Order of the Sword an Shield? It is a national honor society for cyber security professionals.`,
    sword2: `This is a sword. Do you think it will come off of the wall...?`,
    shield: `This shield represents an organization that I joined in 2021. The Order of the Sword an Shield? It is a national honor society for cyber security professionals.`,
    degree1: `This is my Bachelor\'s of Cyber Security and Information Assurance that I received in 2018 from Western Governors University. It was the first time I graduated college. I\'m so proud of it!`,
    degree2: 'This is my Master\'s of Cyber Security and Information Assurance that I received in 2020 from Western Governors University as well. This one covered a lot to topics related to GRC. It was a lot of hard work.',
    degree3: 'This is my Bachelor\'s of Computer Science that I received in 2023 from Western Governors University. This one was very difficult to get. But I learned so very much while working on it.',
    degree4: 'This is actually the degree I have in progress at the moment. My Master\'s of Business Administration with a focus on Information Technology. Also from Western Governors University. I should hopefully be graduated by July of 2024!',
    comptia1: 'This certification is one that I believe all people should possess, that being the CompTIA A+. Every person should have the base level knowledge on how the inner workings of computers operate. It really helps for all facets of not just IT but for life in modern societies as well.',
    comptia2: 'I got the CompTIA Security+ as one of my personal pre-requisites before going to college for Cyber Security. It being an agnostic approach to the information greatly helped with understanding broader landscapes later in time. ',
    comptia3: 'The CompTIA Project+ is a certification that I obtained during my undergrad in WGU as part of the curriculum. It taught me a lot about project management. It does not expire.',
    comptia4: 'I had been doing certification training for quite a few years by the time I got around to going backwards to get the CompTIA Netowrk+ certification. The agnostic approach CompTIA has is priceless in the IT industry. ',
    lpic1: 'The second certification that I ever got was the Linux Professional Institute\'s Certified Administrator. This would actually become invaluable over my time in not only IT but in my personal life and understanding of operating systems.',
    aws1: 'Ahhh, everyone\'s first AWS certificate. The AWS Cloud Practicioner. This is a really great certification to have as it gives a great 10,000 foot view of the cloud architecture landscape and how to utilize it. I got this when I started working at AWS in April of 2021. There is acutally a really cool way to re-certify using the CloudQeuest game now. That makes it way easier.',
    aws2: 'I went for the AWS Certified Solutions Architect Associate certifcation second as I thought it would give me a more in depth understading of how to utilize cloud technologies. I got this certification in July of 2021.',
    aws3: 'At the time I was doing this certification, I was working as a Cloud Support Engineer at AWS for the security services. It was not a requirement to become certified but I got this AWS Security Specialty anyway because I thought it might help. I got this certification in August of 2021.',
    aws4: 'After the AWS Security Specialty, I decided that I needed an even more in depth certification for a better understading of the cloud. I went fot the AWS Certified Solutions Architect Professional to achieve this. That test was not easy I got this certification in February of 2022.',
    aws5: 'At this point I had decided that I wanted the entire honeycomb of AWS. I picked the AWS Database Specialty certification next. I did this because of the old saying that \"who controls the data controls the world.\" I don\'t control the world but I do know how to use RDS and DynamoDB really well. I got this certification in February of 2022 as well. This was an intense month!',
    aws6: 'The AWS Advanced Networking Specialty is a nightmare! I am not embarrassed to say that I did not pass this test until my fourth attempt. It is widely known as the most difficult of the specialties. This is due to the nature of cloud networking as opposed to traditional adrdressing schemes. Cloud is almost purely software based. I got this certification in May of 2022.',
    aws7: 'I went ahead and decided after networking to finish out the professional certifications by getting the AWS DevOps Engineer Professional. This certifcation has a lot to offer as far as an understanding of how to keep your infrastructure automatically running and up to date. I would later utilize this knowledge in my next role as a DevOps Engineer in Selling Partner Services. I got this certification in July of 2022.',
    aws8: 'After having completed both of the professional certifications I decided to clean up the rest of the lower level certifications. I started by getting the AWS Certified SysOps Administrator Associate. Which, as far as a test to me is the best one. It had the labs in it as well as covering a wide array of cloud usage in a general IT role. I got this certification in August of 2022.',
    aws9: 'The last of the lower level certifcations that I had yet to get was the AWS Certified Developer Associate. This one really helped me in my role as a DevOps Support Engineer for Selling Partner Services. This one went more over the creation of infrastructure using Cloud9 and AWS CloudFormation as opposed to maintaining the already constructed materials in the DevOps Engineer Professional. I got this certification in November of 2022 after I transistioned out of AWS to Selling Partner Services.',
    aws10: 'The next logical step was to finish out the specialties so I went to the AWS Certified Machine Learning Specialty. I\'ll admit that I did not know a whole lot about this when I went into this one. But oh did I learn so much about how to utilize Sagemaker to build, train, and test ML models. I still use the knowledge I gained from the training today with all the new AI in the world. I  got this certification in January of 2023.',
    aws11: 'It has to be said again that who controls the data controls the world. But the person that knows how to manipulate the data is the person that controls perception. The AWS Certified Data Analytics Specialty helped me to understand this concept better. This certification went over things like ETL and how to do this by using AWS services like AWS Glue. I still do data manipulation using Python today for better understanding. I got this certification in January of 2023 as well.',
    aws12: 'To finish out the last of the AWS certifications was the SAP on AWS Specialty. This one is a very nuanced and niche certification due to the fact that SAP is everywhere but nobody seems to notice them. The company flies under the radar but is everywhere. I learned a lot about how human capital and supply chain is supported during this certification. It also teaches how to utilize the setups that SAP has created within their company as well. I got this certification in April of 2023 to finish the honeycomb.',
    eccouncil3: 'The first EC-Council certifcation that I achieved was the EC-Council Certified Ethical Hacker. This was the last certification I got before I went to college for a security degree. This certification is a good foundation to get acquainted with information security. I got this certification for the first time in July of 2017 and got it again as part of my Master\'s degree in Cyber Security in August of 2021.',
    eccouncil2: 'For the curriculum for WGU\'s Bachelor of Science in Cyber Security certifications are built in. The EC-Council Certified Incident Handler was one that I got in 2021. It is designed to help people better understand how to triage and do root cause analysis on security incidents. It really helps if you want to go into security operations.',
    eccouncil1: 'The Certified Encryption Specialist from the EC-Council is a certification I got during my undergrad degree as part of the curriculum. It goes into a deeper understandnig of how to utilize encryption in all facets of data protection. It does not go as far as deep into the mathematics for the specific algorithms but it does help get a good understanding of which ones to use and what the tradeoffs are. I got this certification in 2017 as well.',
    eccouncil4: 'The last certification tha I got from the EC-Council was the Certified Hacking Forensics Invistigator in 2021 as part of my Master\'s in Cyber Security. I really loved this one as it taught not just the investigation tools that are used in the business but also the procedures that you use throughout the non-technical portions. Things like first-responder training, how to be an expert witness, and transporation of evidence with chanin of command. It was awesome!',
    splunk: 'What can really be said about Splunk? It is a SIEM that is widely known and oh so very useful. I did not really know what it was when I first got out of college the first time. But after looking into what one does in a SOC, I found a free course from the Splunk organization and decided to take it. It taught the basics of how to search through security logs using the platform. I really enjoyed getting to know how utilize Splunk. I kind of reminds me of WireShark a little bit. I got this certification in 2018.',
    ciw1: 'During the course of my time at WGU during my undergrad degree, I got to learn about the basics of Cyber Security. One of the certifications that was part of the curriculum was that of the CIW Certified Web Security Associate. This certification teaches the basics of web security from attacks such as XSS and SQLi and how to protect against them. I got this certification in 2017.',
    ciw2: 'There is another certifiation from the CIW that is part of the curriculum for WGU during my undergrad degree. The CIW Certified Internet Web Site Developer Assiciate. This certification is a good foundation to get acquainted with web development and web site construction. It gets you acquainted with how to utilize HTML and CSS quite well. I got this certification in 2017 as well.',
    dellemc: 'This certification I\'ll admit I got because I really wanted the title. Getting to call myself a Data Scientist is awesome! The knowledge obtained through the Dell/EMC Data Science and Analytics Associate certification is a very valuable tool to have in the modern data driven world. While studying for this test I learned how to use tools like Tableau to show interpretations of data in more than just data sets. I also learned the basics of the R language for data exploration and manipulation. I got this certifcation in 2017',
    oraclejava: 'I was in the process of going through the professional path of <a href="https://www.codecademy.com/" target="_blank">Codecademy.com</a> when I started the Oracle Java Professional Certificate. During my training I found that Java was one of the most widely used programming languages out there. Which is why I decided to go after this certificate. It is quite old at this point being in Java 7 but it was still fun getting to know that information. I got this certification in 2017.',
    lpic: 'Linux is the operating system that the world needs but not the one it gets. Aside from being the predominant operating system that runs the entirety of the cloud. I pursuerd the Linux Professional Institute\'s Level 2 certification for networking to learn more in depth how to better use Linux and increase my technological understanding. I got this certification in 2021.',
    itil: 'The ITIL Foundations certification is part of the curriculum for WGU in the undergrad degree for Cyber Security. This certification teaches you quite a few different things about how busineses operate. The main thing I remember is that of change management which I didin\'t know about before I got this certification. I got this certification in 2017 as well.',
    isc2: 'Ahh, the Inernational Information Security Systems Certification Consortium or ISC squared for short is considered the platinum standard for security certifications the world over. During my undergrad in Cyber Security I obtained the rank of Associate of the consortium after passing the test for the the Systems Security Certified Practicioner. I can say that this assocation was a good introduction to the certifications idealogy that is used in the industry as far as experience and maintenance. This association was obttained in 2018.',
    ccent: 'This was the very first certification that I ever got. A Cisco Certified Entry Networking Associate. I didn\'t know at the time that this would be the beginning of a life changing journey.',
    ccna1: 'This was the second certification that I got. A Cisco Certified Networking Associate in Routing and Switching. It expired back in 2018 but I still have a lot of knowledge about the subject.',
    ccna2: 'Early on in my certifcation journey I wanted to focus more on the security side of things. So I went after the Cisco Certified Networking Associate for Security in 2016. I remember this certification really well because during my study I actually built my very own tiny VPN as a test case. It was awesome to see the encrypted data go from one end of my little network in Packet Tracer to the other.',
    throne: 'This is where I sit and ponder sometimes admiring all of the knowledge I have attained throughout my life.',
    dude: 'It is dangerous to go alone, you should take a sword. If you can get it off of the wall.',
    bookshelf: 'What\'s on this bookshelf you may ask... mostly the Wheel of Time books. But also a lot of Cyber Security books.',
    blood1: 'This is actually just some red paint.',
    blood2: 'You can\'t get anywhere in life without a little blood, sweat or tears.',
    torture: 'Sometimes all of this studying can seem like a torture.',
    grave: 'Congratulations! You found an Easter Egg! I was curious if anybody would find that hole in the wall.'
};
  